# Generated by Django 3.2.7 on 2021-10-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('recommended', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('status', models.CharField(choices=[('F', 'Faculty'), ('UG', 'Undergraduate'), ('G', 'Graduate')], max_length=2)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
